"""FinTech Algorithmic Trading Risk Engine & Monte Carlo VaR Analyzer."""

from fintech_algorithmic_trading.backtest import BacktestEngine
from fintech_algorithmic_trading.data import MarketDataFeed
from fintech_algorithmic_trading.engine.evt import EVTEngine, calculate_evt_var
from fintech_algorithmic_trading.engine.greeks import calculate_option_greeks
from fintech_algorithmic_trading.engine.hedging import OptionHedgingEngine
from fintech_algorithmic_trading.engine.monte_carlo import MonteCarloEngine
from fintech_algorithmic_trading.engine.optimizer import PortfolioOptimizer
from fintech_algorithmic_trading.engine.risk_engine import PortfolioRiskEngine
from fintech_algorithmic_trading.engine.sizing import PositionSizer
from fintech_algorithmic_trading.engine.var import (
    VaRCalculator,
    calculate_cornish_fisher_var,
    calculate_historical_var,
    calculate_parametric_var,
)
from fintech_algorithmic_trading.execution import (
    OrderManagementSystem,
    PreTradeRiskGatekeeper,
    SlippageModel,
)
from fintech_algorithmic_trading.reporting import DataExporter, RiskReportGenerator
from fintech_algorithmic_trading.storage.repository import PortfolioRepository
from fintech_algorithmic_trading.strategy import (
    AlphaStrategy,
    CompositeAlphaAggregator,
    MeanRevertingBollingerStrategy,
    PairsStatArbStrategy,
    TrendFollowingMACDStrategy,
    VolatilityBreakoutStrategy,
)
from fintech_algorithmic_trading.surveillance import RiskSurveillanceMonitor
from fintech_algorithmic_trading.types import (
    AlertSeverity,
    Asset,
    AssetClass,
    BacktestConfig,
    BacktestMetrics,
    BacktestResult,
    BacktestTrade,
    Bar,
    CircuitBreakerState,
    DeltaGammaHedge,
    DriftModel,
    EVTResult,
    ExecutionReport,
    Fill,
    KellyCriterionMode,
    KellySizingResult,
    MonteCarloConfig,
    MonteCarloResult,
    OptimizationObjective,
    OptimizationResult,
    OptionContract,
    OptionGreeks,
    OptionType,
    Order,
    OrderBookDepth,
    OrderBookLevel,
    OrderSide,
    OrderStatus,
    OrderType,
    Portfolio,
    PortfolioGreeks,
    Position,
    PositionType,
    Quote,
    RiskAlert,
    RiskComplianceReport,
    RiskLimits,
    RiskViolation,
    SignalDirection,
    StrategySignal,
    StressScenario,
    StressTestResult,
    SurveillanceReport,
    TargetAllocation,
    TimeInForce,
    VaRMethod,
    VaRResult,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "AlertSeverity",
    "AlphaStrategy",
    "Asset",
    "AssetClass",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestMetrics",
    "BacktestResult",
    "BacktestTrade",
    "Bar",
    "CircuitBreakerState",
    "CompositeAlphaAggregator",
    "DataExporter",
    "DeltaGammaHedge",
    "DriftModel",
    "EVTEngine",
    "EVTResult",
    "ExecutionReport",
    "Fill",
    "KellyCriterionMode",
    "KellySizingResult",
    "MarketDataFeed",
    "MeanRevertingBollingerStrategy",
    "MonteCarloConfig",
    "MonteCarloEngine",
    "MonteCarloResult",
    "OptionContract",
    "OptionGreeks",
    "OptionHedgingEngine",
    "OptionType",
    "OptimizationObjective",
    "OptimizationResult",
    "Order",
    "OrderBookDepth",
    "OrderBookLevel",
    "OrderManagementSystem",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PairsStatArbStrategy",
    "Portfolio",
    "PortfolioGreeks",
    "PortfolioOptimizer",
    "PortfolioRepository",
    "PortfolioRiskEngine",
    "Position",
    "PositionSizer",
    "PositionType",
    "PreTradeRiskGatekeeper",
    "Quote",
    "RiskAlert",
    "RiskComplianceReport",
    "RiskLimits",
    "RiskReportGenerator",
    "RiskSurveillanceMonitor",
    "RiskViolation",
    "SignalDirection",
    "SlippageModel",
    "StrategySignal",
    "StressScenario",
    "StressTestResult",
    "SurveillanceReport",
    "TargetAllocation",
    "TimeInForce",
    "TrendFollowingMACDStrategy",
    "VaRCalculator",
    "VaRMethod",
    "VaRResult",
    "VolatilityBreakoutStrategy",
    "calculate_cornish_fisher_var",
    "calculate_evt_var",
    "calculate_historical_var",
    "calculate_option_greeks",
    "calculate_parametric_var",
]
